version: "3"

vars:
  CONTAINER_TOOL: podman
  COVERAGE_FILE: ./test/cover.out

tasks:

  # TESTING

  test:
    desc: Test all packages
    requires:
      vars:
        - COVERAGE_FILE
        - name: CONTAINER_TOOL
          enum: [docker, podman]
    cmd: sh scripts/testing.sh {{.CONTAINER_TOOL}} {{.COVERAGE_FILE}}
  
  test-coverage:
    desc: Generates coverage html after testing
    aliases: [cover]
    deps:
      - test
    cmd: go tool cover -html="{{.COVERAGE_FILE}}"

  mock:
    desc: Generates all mocks
    cmd: go generate $INTERNAL_WILDCARD

  # TOOLS

  lint:
    desc: Lint all files
    cmds: 
      - fieldalignment -fix $INTERNAL_WILDCARD
      - gosec ./...
    ignore_error: true
      
  graph:
    desc: Generate dependency graph in pdf
    cmd: go mod graph | modgraphviz | dot -Tpdf -o graph.pdf

  docker-test-up:
    desc: Run docker containers for testing
    cmd: docker compose -f ./test/compose/dgraph.yml up --force-recreate --remove-orphans --detach

  docker-test-down:
    desc: Kill docker containers for testing
    cmd: docker compose -f ./test/compose/dgraph.yml down