version: "3"

env:
  # coverage file
  COVERAGE_FILE: ./test/cover.out

tasks:

  # TESTING

  test:
    desc: Test all packages
    cmd: sh scripts/testing.sh $COVERAGE_FILE
  
  test-coverage:
    desc: Generates coverage html after testing
    aliases: [cover]
    deps:
      - test
    cmd: go tool cover -html="$COVERAGE_FILE"

  mock:
    desc: Generates all mocks
    cmd: go generate $INTERNAL_WILDCARD

  # TOOLS

  lint:
    desc: Lint all files
    cmds: 
      - fieldalignment -fix $INTERNAL_WILDCARD
      - gosec ./...
    ignore_error: true
      
  graph:
    desc: Generate dependency graph in pdf
    cmd: go mod graph | modgraphviz | dot -Tpdf -o graph.pdf

  docker-test-up:
    desc: Run docker containers for testing
    cmd: docker compose -f ./test/compose/docker-compose.yml up --force-recreate --remove-orphans --detach

  docker-test-down:
    desc: Kill docker containers for testing
    cmd: docker compose -f ./test/compose/docker-compose.yml down